services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:9090"]
    volumes:
      - .:/app
    ports:
      - "9090:9090"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
      
  celery:
    build: .
    user: django-user
    command: ["celery", "-A", "djangocelery", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis

  celerybeat:
    build: .
    user: django-user
    command: ["celery", "-A", "djangocelery", "beat", "--loglevel=info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
    volumes:
      - .:/app
    depends_on:
      - redis